name: Testing Actions

#  Replase the fallowing according to your needs
# CRON_TIME: '00 00 * * *'
# GITHUB_USERNMAE: 'bin0x00'
# GITHUB_REPO: 'everday-action-commit'

on:
  schedule:  # Everday
    cron: '00 00 * * *'
  repository_dispatch:  # For requests bassed commit
    types: start_action  # <<< WORK HERE

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Getting the repo
      uses: actions/checkout@v2

    - name: Re setting the url for `origin`
      run: |
        git remote set-url origin https://bin0x00:${{ secrets.GITHUB_TOKEN }}@github.com/everday-action-commit/ol3-1.git

    - name: Creating an empty commit 
      run: |
        git commit --allow-empty -m "My amazing commit"
    
    - name: Finilly pushing the repo
      run: |
        git push origin master
