name: Testing Actions

#  Replase the fallowing according to your needs
# GITHUB_USERNMAE: 'bin0x00'
# GITHUB_REPO: 'everday-action-commit'
#
# CRON_TIME: '00 00 * * *'

on:
  schedule:  # Everday
    - cron: '00 00 * * *'
  repository_dispatch:  # For requests bassed commit
    types: start_action  # <<< WORK HERE

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Getting the repo
      uses: actions/checkout@v2

    - name: Re setting the url for `origin`
      run: |
        git remote set-url origin https://bin0x00:${{ secrets.GITHUB_TOKEN }}@github.com/bin0x00/everday-action-commit.git

    - name: Adding git info
      run: |
        git config --global user.name "bin0x00"
        git config --global user.email "${{ secrets.EMAIL }}"  # Added email in secrets


    - name: Creating an empty commit 
      run: |
        git commit --allow-empty -m "My amazing commit"
    
    - name: Finilly pushing the repo
      run: |
        git push origin master
